### ISSUE TITLE
🐛 Bug Report: Param "userId" is not optional

### ISSUE THREAD

**Issue by jofftiquez** [appwrite/demo-todo-with-vue#33]
### 👟 Reproduction steps

Just create a new account in Signup

### 👍 Expected behavior

Signing up should go through with new credentials

### 👎 Actual Behavior

Getting error:

![image](https://user-images.githubusercontent.com/8638243/157351538-260e7fdf-0671-412b-a111-f1956d8a378d.png)

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

This is the demo app

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by wiktorcie** [comment]
I'm getting cors issues on localhost, not sure if that's related.
or ```URL constructor: localhost/api/v1/account is not a valid URL.```

**Comment by jofftiquez** [comment]
> I'm getting cors issues on localhost, not sure if that's related. or `URL constructor: localhost/api/v1/account is not a valid URL.` Any clues how to resolve?

Haven't retested again myself yet.

**Comment by rumbis** [comment]
i got the same issue

**Comment by stnguyen90** [comment]
@jofftiquez, is this still a problem? It looks like the code has been updated to pass a userId: 

https://github.com/appwrite/demo-todo-with-vue/blob/1b8f2d13b9ed591801405cda4a9acb7ab9a6c2f9/src/api/index.js#L21

**Comment by jofftiquez** [comment]
> @jofftiquez, is this still a problem? It looks like the code has been updated to pass a userId:
> 
> https://github.com/appwrite/demo-todo-with-vue/blob/1b8f2d13b9ed591801405cda4a9acb7ab9a6c2f9/src/api/index.js#L21

Hello, sorry but I haven't tested it myself again.

**Comment by stnguyen90** [comment]
@jofftiquez is it okay if I close this and you can open a new issue if you're still running into this problem?

**Comment by jofftiquez** [comment]
Sure thing! @stnguyen90
